### PR TITLE
make plugin service broker aware

### PR DESCRIPTION
**Pull request by PG2000**
- this solves the case when mutliple service brokers offers a service with the same name

Signed-off-by: Patrick Geschinski <PG2000@users.noreply.github.com>

### CODE REVIEW

**Comment by PG2000** [comment]
@glyn @spikymonkey Sorry for the noise 

Any chance that this PR can be merged?
Or is this repo not actively maintained anymore.

**Comment by glyn** [comment]
> @glyn @spikymonkey Sorry for the noise
> 
> Any chance that this PR can be merged? Or is this repo not actively maintained anymore.

I have retired, so I'm not maintaining this repo. I'm afraid.

**Comment by PG2000** [comment]
Maybe one of 
@ojhughes, @csterwa , @mheath, @chrisjs 
could help out here?

**Comment by spikymonkey** [comment]
Hi @PG2000, thanks very much for contributing this and I'm sorry it's taken me so long to get back to you. I'm focused on other things at the moment but hopefully we can get this integrated for you fairly soon. The code all looks good to me and I can see all the tests pass, but I hit a  weird websocket disconnection issue while testing manually - I think it's probably completely unrelated to your change but I'll need to get to the bottom of that before I can merge it. Then I think either @csterwa or @candicenonsense will be able to help us out with a new plugin release.

**Comment by PG2000** [comment]
> Hi @PG2000, thanks very much for contributing this and I'm sorry it's taken me so long to get back to you. I'm focused on other things at the moment but hopefully we can get this integrated for you fairly soon. The code all looks good to me and I can see all the tests pass, but I hit a weird websocket disconnection issue while testing manually - I think it's probably completely unrelated to your change but I'll need to get to the bottom of that before I can merge it. Then I think either @csterwa or @candicenonsense will be able to help us out with a new plugin release.

Hey @spikymonkey,
thanks for finding time to take care of this 
I appreciate this very much.

I observed the same behaviour (web socket disconnects) with the current stable version of this plugin. So I hope you can find the issue 🙂. I couldn't find it on my own and would be happy if this works again. Thanks for that.

**Comment by spikymonkey** [comment]
> I observed the same behaviour (web socket disconnects) with the current stable version of this plugin

Yep, that's odd, but I see the same results as you - it's happening with the build from `main`. So on that basis I think there's no reason to hold up the merge of this PR. Hopefully we can get to the bottom of that disconnection, but for now, thank you again and sorry this took so long!

**Pull request merged**
