### PR TITLE
Revert "make plugin service broker aware"

### PR DESCRIPTION
**Pull request by spikymonkey**
Sorry @PG2000 - I jumped the gun and realised that we need to ask you to sign the CLA before we can integrate this. We're just waiting on CLA bot integration to be set up for this repo.

Reverts pivotal-cf/service-instance-logs-cli-plugin#29

### CODE REVIEW

**Comment by PG2000** [comment]
@spikymonkey I signed it now. I think I did it correctly. Where can I see it? What would be the next steps? Should I create a new Pull Request?

**Comment by spikymonkey** [comment]
Thanks @PG2000! @candicenonsense would you be able to help us out with this one please?

**Comment by candicenonsense** [comment]
@spikymonkey Yes, will try to help this along.  @PG2000 I think a new pull request might have the smallest amount of git trouble involved.

**Comment by PG2000** [comment]
@candicenonsense and @spikymonkey thanks for your help.
I opened a new PR #32

**Pull request merged**
